import type { Locale } from "@/lib/i18n/config";

export type PolicySection = { heading: string; paragraphs: string[] };
export type PolicyDocument = { title: string; intro: string; sections: PolicySection[] };

/** Drafted from what the app actually does today: local email/password accounts,
 * an LLM-backed AI Pastor, private journals and prayers, optional web push, and
 * opt-in Circles. Not written by a lawyer — see README before public launch. */
const TERMS: Record<Locale, PolicyDocument> = {
  id: {
    title: "Syarat & Ketentuan",
    intro:
      "Livyn adalah pendamping rohani harian. Dengan membuat akun dan memakai Livyn, kamu menyetujui hal-hal di bawah ini.",
    sections: [
      {
        heading: "1. Siapa yang boleh memakai Livyn",
        paragraphs: [
          "Livyn ditujukan untuk pemakaian pribadi dan non-komersial. Kalau kamu berusia di bawah 13 tahun, gunakan Livyn dengan pendampingan orang tua atau wali.",
          "Kamu bertanggung jawab menjaga kerahasiaan kata sandimu dan atas semua aktivitas yang terjadi lewat akunmu.",
        ],
      },
      {
        heading: "2. AI Pastor bukan pengganti manusia",
        paragraphs: [
          "AI Pastor adalah program komputer. Jawabannya dihasilkan oleh model bahasa dan bisa keliru, tidak lengkap, atau tidak sesuai dengan ajaran gerejamu.",
          "AI Pastor bukan pengganti gembala, konselor, psikolog, dokter, atau tenaga profesional lainnya. Jangan memakai Livyn untuk keadaan darurat.",
          "Kalau kamu sedang dalam krisis atau berpikir untuk menyakiti dirimu sendiri, segera hubungi layanan darurat setempat atau orang yang kamu percaya.",
        ],
      },
      {
        heading: "3. Isi yang kamu tulis",
        paragraphs: [
          "Jurnal, doa pribadi, dan catatanmu tetap milikmu. Kami tidak mengklaim kepemilikan atasnya.",
          "Isi yang kamu bagikan ke Circle atau kirim ke teman akan terlihat oleh anggota Circle atau teman tersebut. Pikirkan sebelum membagikan sesuatu yang sangat pribadi.",
          "Dilarang mengunggah isi yang melanggar hukum, membenci, melecehkan, atau melanggar hak orang lain. Kami dapat menghapus isi seperti itu dan menutup akun yang melakukannya.",
        ],
      },
      {
        heading: "4. Isi Alkitab dan pihak ketiga",
        paragraphs: [
          "Teks Alkitab, gambar latar, dan khotbah dapat berasal dari penyedia pihak ketiga dan tunduk pada ketentuan mereka masing-masing.",
          "Livyn menggunakan layanan pihak ketiga untuk menjalankan AI Pastor dan mengirim notifikasi. Isi percakapanmu dengan AI Pastor dikirim ke penyedia model bahasa agar jawabannya bisa dihasilkan.",
        ],
      },
      {
        heading: "5. Layanan diberikan apa adanya",
        paragraphs: [
          "Livyn masih dikembangkan dan diberikan “apa adanya”, tanpa jaminan bahwa layanan akan selalu tersedia, bebas galat, atau bebas kehilangan data.",
          "Sejauh diizinkan hukum, kami tidak bertanggung jawab atas kerugian yang timbul dari pemakaian atau ketidaktersediaan Livyn.",
        ],
      },
      {
        heading: "6. Perubahan dan penutupan akun",
        paragraphs: [
          "Kami dapat mengubah ketentuan ini. Kalau perubahannya berarti, kami akan meminta persetujuanmu lagi saat kamu membuka aplikasi.",
          "Kamu boleh berhenti kapan saja. Hubungi kami untuk menghapus akun beserta datanya.",
        ],
      },
    ],
  },
  en: {
    title: "Terms & Conditions",
    intro:
      "Livyn is a daily spiritual companion. By creating an account and using Livyn, you agree to the following.",
    sections: [
      {
        heading: "1. Who may use Livyn",
        paragraphs: [
          "Livyn is intended for personal, non-commercial use. If you are under 13, use Livyn with a parent or guardian.",
          "You are responsible for keeping your password confidential and for all activity that happens through your account.",
        ],
      },
      {
        heading: "2. AI Pastor is not a substitute for a person",
        paragraphs: [
          "AI Pastor is a computer program. Its answers are generated by a language model and can be wrong, incomplete, or out of step with your church's teaching.",
          "AI Pastor does not replace a pastor, counsellor, psychologist, doctor, or any other professional. Do not use Livyn in an emergency.",
          "If you are in crisis or thinking of harming yourself, contact your local emergency services or someone you trust straight away.",
        ],
      },
      {
        heading: "3. Content you write",
        paragraphs: [
          "Your journal, personal prayers, and notes remain yours. We claim no ownership over them.",
          "Anything you share to a Circle or send to a friend becomes visible to those people. Think before sharing something deeply private.",
          "Do not upload content that is unlawful, hateful, harassing, or infringes someone else's rights. We may remove such content and close the accounts responsible.",
        ],
      },
      {
        heading: "4. Scripture and third-party content",
        paragraphs: [
          "Bible text, background images, and sermons may come from third-party providers and remain subject to their own terms.",
          "Livyn relies on third-party services to run AI Pastor and deliver notifications. Your AI Pastor conversations are sent to a language-model provider so that a reply can be generated.",
        ],
      },
      {
        heading: "5. Service provided as-is",
        paragraphs: [
          "Livyn is under active development and is provided \"as is\", with no guarantee that it will always be available, error-free, or free from data loss.",
          "To the extent permitted by law, we are not liable for losses arising from your use of, or inability to use, Livyn.",
        ],
      },
      {
        heading: "6. Changes and closing your account",
        paragraphs: [
          "We may update these terms. If a change is significant, we will ask for your agreement again the next time you open the app.",
          "You may stop at any time. Contact us to delete your account and its data.",
        ],
      },
    ],
  },
};

const PRIVACY: Record<Locale, PolicyDocument> = {
  id: {
    title: "Kebijakan Privasi",
    intro:
      "Kebijakan ini menjelaskan data apa yang Livyn simpan, kenapa, dan apa yang bisa kamu lakukan terhadapnya.",
    sections: [
      {
        heading: "1. Data yang kami simpan",
        paragraphs: [
          "Data akun: nama, alamat email, dan kata sandi yang disimpan dalam bentuk hash (kami tidak pernah menyimpan kata sandi aslinya).",
          "Isi yang kamu buat: jurnal, doa pribadi, ayat favorit, catatan, sorotan, dan pengingat doa.",
          "Data pemakaian: riwayat masuk (waktu, alamat IP, jenis perangkat) untuk keamanan akun, serta jam kamu biasanya membuka aplikasi untuk fitur pengingat pintar.",
          "Data komunitas: keanggotaan Circle, permintaan doa yang kamu bagikan, dan ayat yang kamu kirim ke teman.",
        ],
      },
      {
        heading: "2. Kenapa kami menyimpannya",
        paragraphs: [
          "Untuk menjalankan fitur yang kamu pakai, menjaga keamanan akunmu, dan mengirim pengingat yang kamu aktifkan sendiri.",
          "Kami tidak menjual datamu, dan tidak memakainya untuk iklan.",
        ],
      },
      {
        heading: "3. Siapa yang bisa melihat",
        paragraphs: [
          "Jurnal dan doa pribadimu bersifat pribadi. Isi tersebut tidak ditampilkan ke pengguna lain.",
          "Yang kamu bagikan ke Circle terlihat oleh anggota Circle itu. Yang kamu kirim ke teman terlihat oleh teman itu.",
          "Percakapanmu dengan AI Pastor dikirim ke penyedia model bahasa untuk menghasilkan jawaban. Jangan menuliskan data yang sangat sensitif di sana.",
        ],
      },
      {
        heading: "4. Notifikasi",
        paragraphs: [
          "Notifikasi push hanya aktif kalau kamu mengizinkannya. Kami menyimpan alamat langganan push perangkatmu supaya bisa mengirim pesan, dan menghapusnya begitu kamu mematikan notifikasi.",
        ],
      },
      {
        heading: "5. Penyimpanan dan penghapusan",
        paragraphs: [
          "Data disimpan di layanan basis data terkelola (Supabase) dan aplikasi berjalan di Vercel.",
          "Kamu bisa meminta penghapusan akun beserta seluruh datanya. Setelah dihapus, isi jurnal dan doamu tidak bisa dipulihkan.",
        ],
      },
      {
        heading: "6. Menghubungi kami",
        paragraphs: [
          "Kalau ada pertanyaan tentang data pribadimu, hubungi kami lewat alamat kontak yang tercantum di halaman Profil.",
        ],
      },
    ],
  },
  en: {
    title: "Privacy Policy",
    intro: "This policy explains what Livyn stores, why, and what you can do about it.",
    sections: [
      {
        heading: "1. What we store",
        paragraphs: [
          "Account data: your name, email address, and a hashed password (we never store the password itself).",
          "Content you create: journals, personal prayers, favourite verses, notes, highlights, and prayer reminders.",
          "Usage data: sign-in history (time, IP address, device type) for account security, and the hours you usually open the app, which powers smart reminders.",
          "Community data: your Circle memberships, prayer requests you share, and verses you send to friends.",
        ],
      },
      {
        heading: "2. Why we store it",
        paragraphs: [
          "To run the features you use, keep your account secure, and deliver the reminders you switched on yourself.",
          "We do not sell your data, and we do not use it for advertising.",
        ],
      },
      {
        heading: "3. Who can see it",
        paragraphs: [
          "Your journal and personal prayers are private. They are not shown to other users.",
          "What you share to a Circle is visible to that Circle's members. What you send to a friend is visible to that friend.",
          "Your AI Pastor conversations are sent to a language-model provider so a reply can be generated. Avoid writing highly sensitive details there.",
        ],
      },
      {
        heading: "4. Notifications",
        paragraphs: [
          "Push notifications are only active if you allow them. We store your device's push subscription so we can deliver messages, and delete it as soon as you turn notifications off.",
        ],
      },
      {
        heading: "5. Storage and deletion",
        paragraphs: [
          "Data is held in a managed database service (Supabase) and the app runs on Vercel.",
          "You can request deletion of your account and all its data. Once deleted, your journal and prayer content cannot be recovered.",
        ],
      },
      {
        heading: "6. Contacting us",
        paragraphs: [
          "If you have questions about your personal data, reach us at the contact address listed on the Profile page.",
        ],
      },
    ],
  },
};

export function getTermsDocument(locale: Locale): PolicyDocument {
  return TERMS[locale] ?? TERMS.id;
}

export function getPrivacyDocument(locale: Locale): PolicyDocument {
  return PRIVACY[locale] ?? PRIVACY.id;
}

/** The short summary shown on the consent screen itself, above the checkbox. */
export const CONSENT_SUMMARY: Record<Locale, string[]> = {
  id: [
    "Livyn adalah pendamping rohani harian, bukan penyedia layanan medis atau konseling profesional.",
    "AI Pastor dihasilkan oleh model bahasa dan bisa keliru. Jangan memakainya untuk keadaan darurat.",
    "Jurnal dan doa pribadimu bersifat pribadi dan tidak dibagikan tanpa izinmu.",
    "Yang kamu bagikan ke Circle atau kirim ke teman akan terlihat oleh mereka.",
  ],
  en: [
    "Livyn is a daily spiritual companion, not a medical or professional counselling service.",
    "AI Pastor is generated by a language model and can be wrong. Do not use it in an emergency.",
    "Your journal and personal prayers stay private and are not shared without your permission.",
    "Anything you share to a Circle or send to a friend becomes visible to them.",
  ],
};
