// Curated verse text for a devotionally representative set of
// chapters/passages. This is an original Livyn rendering in plain
// Indonesian — NOT a verbatim reproduction of any single copyrighted
// translation (e.g. LAI's Terjemahan Baru). Loading the full 66-book /
// ~31,000-verse canon requires a licensed text source (LAI, YouVersion/
// API.Bible, etc.) — see README for how to wire one in.
export const BIBLE_TEXT: Array<{ book: string; chapter: number; verses: [number, string][] }> = [
  {
    book: "kej",
    chapter: 1,
    verses: [
      [1, "Pada mulanya Allah menciptakan langit dan bumi."],
      [2, "Bumi belum berbentuk dan kosong, gelap gulita menutupi samudera raya, dan Roh Allah melayang-layang di atas permukaan air."],
      [3, "Berfirmanlah Allah, \"Jadilah terang,\" maka terang itu jadi."],
      [4, "Allah melihat bahwa terang itu baik, lalu dipisahkan-Nya terang itu dari gelap."],
      [5, "Allah menamai terang itu siang, dan gelap itu malam. Jadilah petang dan pagi, itulah hari pertama."],
      [6, "Berfirmanlah Allah, \"Jadilah cakrawala di tengah air, yang memisahkan air dari air.\""],
      [7, "Maka Allah menjadikan cakrawala dan memisahkan air yang di bawah cakrawala dari air yang di atasnya. Jadilah demikian."],
      [8, "Allah menamai cakrawala itu langit. Jadilah petang dan pagi, itulah hari kedua."],
      [9, "Berfirmanlah Allah, \"Berkumpullah air yang di bawah langit pada satu tempat, sehingga tampaklah yang kering.\" Jadilah demikian."],
      [10, "Allah menamai yang kering itu darat, dan kumpulan air itu dinamai-Nya laut. Allah melihat bahwa semuanya baik."],
      [11, "Berfirmanlah Allah, \"Hendaklah tanah menumbuhkan tumbuh-tumbuhan dan pohon buah-buahan menurut jenisnya.\" Jadilah demikian."],
      [12, "Tanah itu menghasilkan tumbuh-tumbuhan dan pohon-pohon berbuah, dan Allah melihat bahwa semuanya baik."],
      [13, "Jadilah petang dan pagi, itulah hari ketiga."],
      [14, "Berfirmanlah Allah, \"Hendaklah ada benda-benda penerang pada cakrawala untuk memisahkan siang dari malam, dan menjadi tanda musim, hari, dan tahun.\""],
      [15, "Jadilah demikian, benda-benda penerang itu menerangi bumi."],
      [16, "Allah menjadikan dua benda penerang besar: yang lebih besar untuk menguasai siang, yang lebih kecil untuk menguasai malam, dan bintang-bintang."],
      [17, "Allah menempatkan semuanya pada cakrawala untuk menerangi bumi,"],
      [18, "untuk menguasai siang dan malam, dan memisahkan terang dari gelap. Allah melihat bahwa semuanya baik."],
      [19, "Jadilah petang dan pagi, itulah hari keempat."],
      [20, "Berfirmanlah Allah, \"Hendaklah air dipenuhi makhluk hidup, dan burung-burung beterbangan di atas bumi menghiasi cakrawala.\""],
      [21, "Allah menciptakan makhluk-makhluk besar di laut dan segala makhluk hidup yang bergerak di air, serta burung-burung, masing-masing menurut jenisnya. Allah melihat bahwa semuanya baik."],
      [22, "Allah memberkati semuanya, \"Berkembangbiaklah dan penuhilah air laut, dan bertambah banyaklah burung-burung di bumi.\""],
      [23, "Jadilah petang dan pagi, itulah hari kelima."],
      [24, "Berfirmanlah Allah, \"Hendaklah bumi mengeluarkan makhluk hidup menurut jenisnya: ternak, binatang melata, dan satwa liar.\" Jadilah demikian."],
      [25, "Allah menjadikan semuanya menurut jenisnya, dan Ia melihat bahwa semuanya baik."],
      [26, "Berfirmanlah Allah, \"Marilah Kita menjadikan manusia menurut gambar dan rupa Kita, supaya mereka berkuasa atas segala makhluk di bumi.\""],
      [27, "Maka Allah menciptakan manusia menurut gambar-Nya; laki-laki dan perempuan diciptakan-Nya mereka."],
      [28, "Allah memberkati mereka dan berfirman, \"Berkembangbiaklah, penuhilah bumi, dan taklukkanlah itu; berkuasalah atas semua makhluk hidup.\""],
      [29, "Allah berfirman, \"Kuberikan kepadamu segala tumbuhan berbiji dan pohon berbuah untuk menjadi makananmu.\""],
      [30, "Dan kepada segala binatang di bumi Kuberikan tumbuh-tumbuhan hijau menjadi makanan. Jadilah demikian."],
      [31, "Allah melihat segala yang dijadikan-Nya, sungguh amat baik. Jadilah petang dan pagi, itulah hari keenam."],
    ],
  },
  {
    book: "mzm",
    chapter: 23,
    verses: [
      [1, "TUHAN adalah gembalaku, aku tidak akan kekurangan."],
      [2, "Ia membaringkan aku di padang rumput yang hijau, Ia membimbing aku ke air yang tenang;"],
      [3, "Ia menyegarkan jiwaku, dan menuntunku di jalan yang benar oleh karena nama-Nya."],
      [4, "Sekalipun aku berjalan melalui lembah kekelaman, aku tidak takut bahaya, sebab Engkau besertaku; gada-Mu dan tongkat-Mu, itulah yang menghiburku."],
      [5, "Engkau menyediakan hidangan bagiku di hadapan lawan-lawanku; Engkau mengurapi kepalaku dengan minyak, cawanku penuh melimpah."],
      [6, "Kebajikan dan kemurahan akan mengikuti aku sepanjang umur hidupku, dan aku akan diam dalam rumah TUHAN sepanjang masa."],
    ],
  },
  {
    book: "mzm",
    chapter: 91,
    verses: [
      [1, "Orang yang duduk dalam lindungan Yang Mahatinggi, dan bermalam dalam naungan Yang Mahakuasa,"],
      [2, "berkata kepada TUHAN, \"Tempat perlindunganku dan kubu pertahananku, Allahku yang kupercayai.\""],
      [3, "Sesungguhnya Dialah yang akan melepaskan engkau dari jerat penangkap burung, dari penyakit yang membinasakan."],
      [4, "Dengan kepak-Nya Ia akan menudungi engkau, dan di bawah sayap-Nya engkau akan berlindung; kesetiaan-Nya menjadi perisai dan pagar tembok."],
      [5, "Engkau tak usah takut terhadap kedahsyatan malam, atau panah yang terbang di waktu siang,"],
      [6, "terhadap penyakit sampar yang menjalar dalam gelap, atau terhadap penyakit yang mendatangkan kebinasaan pada waktu tengah hari."],
      [7, "Sekalipun seribu orang rebah di sisimu, dan sepuluh ribu di sebelah kananmu, itu tidak akan menimpa engkau."],
      [8, "Engkau hanya akan melihat dengan matamu sendiri, dan menyaksikan balasan bagi orang-orang fasik."],
      [9, "Sebab engkau telah menjadikan TUHAN, tempat perlindunganmu, Yang Mahatinggi, tempat perteduhanmu,"],
      [10, "malapetaka tidak akan menimpa engkau, dan tulah tidak akan mendekat kepada kemahmu."],
      [11, "Sebab Ia akan memerintahkan malaikat-malaikat-Nya untuk menjaga engkau di segala jalanmu."],
      [12, "Mereka akan menatang engkau di atas tangannya, supaya kakimu jangan terantuk kepada batu."],
      [13, "Singa dan ular berbisa akan kaulangkahi, singa muda dan ular naga akan kauinjak."],
      [14, "\"Karena ia berpegang teguh kepada-Ku, Aku akan meluputkannya; Aku akan membentenginya, sebab ia mengenal nama-Ku.\""],
      [15, "\"Bila ia berseru kepada-Ku, Aku akan menjawabnya; Aku akan menyertainya dalam kesesakan, membebaskan dan memuliakannya.\""],
      [16, "\"Aku akan memuaskannya dengan umur panjang, dan memperlihatkan keselamatan yang dari-Ku kepadanya.\""],
    ],
  },
  {
    book: "mzm",
    chapter: 121,
    verses: [
      [1, "Aku melayangkan mataku ke gunung-gunung; dari manakah akan datang pertolonganku?"],
      [2, "Pertolonganku ialah dari TUHAN, yang menjadikan langit dan bumi."],
      [3, "Ia takkan membiarkan kakimu goyah, Penjagamu takkan terlelap."],
      [4, "Sesungguhnya Penjaga Israel takkan terlelap dan takkan tertidur."],
      [5, "TUHAN adalah Penjagamu, TUHAN adalah naunganmu di sebelah tangan kananmu."],
      [6, "Matahari tidak akan menyakiti engkau pada waktu siang, atau bulan pada waktu malam."],
      [7, "TUHAN akan menjaga engkau dari segala kecelakaan; Ia akan menjaga nyawamu."],
      [8, "TUHAN akan menjaga keluar masukmu, dari sekarang sampai selama-lamanya."],
    ],
  },
  {
    book: "ams",
    chapter: 3,
    verses: [
      [5, "Percayalah kepada TUHAN dengan segenap hatimu, dan janganlah bersandar kepada pengertianmu sendiri."],
      [6, "Akuilah Dia dalam segala lakumu, maka Ia akan meluruskan jalanmu."],
      [11, "Anakku, janganlah engkau menolak didikan TUHAN, dan janganlah engkau bosan akan peringatan-Nya."],
      [12, "Karena TUHAN memberi didikan kepada yang dikasihi-Nya, seperti seorang ayah kepada anak yang disayangi."],
    ],
  },
  {
    book: "pkh",
    chapter: 3,
    verses: [
      [1, "Untuk segala sesuatu ada masanya, dan untuk setiap peristiwa di bawah langit ada waktunya."],
      [2, "Ada waktu untuk lahir, ada waktu untuk meninggal; ada waktu menanam, ada waktu mencabut yang ditanam."],
      [3, "Ada waktu membunuh, ada waktu menyembuhkan; ada waktu merombak, ada waktu membangun."],
      [4, "Ada waktu menangis, ada waktu tertawa; ada waktu meratap, ada waktu menari."],
      [5, "Ada waktu membuang batu, ada waktu mengumpulkan batu; ada waktu memeluk, ada waktu menahan diri."],
      [6, "Ada waktu mencari, ada waktu kehilangan; ada waktu menyimpan, ada waktu membuang."],
      [7, "Ada waktu merobek, ada waktu menjahit; ada waktu berdiam diri, ada waktu berbicara."],
      [8, "Ada waktu mengasihi, ada waktu membenci; ada waktu untuk perang, ada waktu untuk damai."],
    ],
  },
  {
    book: "yes",
    chapter: 41,
    verses: [
      [10, "Janganlah takut, sebab Aku menyertai engkau, janganlah bimbang, sebab Akulah Allahmu; Aku akan meneguhkan, bahkan menolong engkau, Aku akan memegang engkau dengan tangan kanan-Ku yang membawa kemenangan."],
      [13, "Sebab Aku, TUHAN Allahmu, memegang tangan kananmu, dan berkata kepadamu: Janganlah takut, Akulah yang menolong engkau."],
    ],
  },
  {
    book: "yer",
    chapter: 29,
    verses: [
      [11, "Sebab Aku ini mengetahui rancangan-rancangan apa yang ada pada-Ku mengenai kamu, demikianlah firman TUHAN, yaitu rancangan damai sejahtera dan bukan rancangan kecelakaan, untuk memberikan kepadamu hari depan yang penuh harapan."],
      [12, "Apabila kamu berseru dan datang untuk berdoa kepada-Ku, maka Aku akan mendengarkan kamu."],
      [13, "Apabila kamu mencari Aku, kamu akan menemukan Aku, apabila kamu mencari Aku dengan segenap hatimu."],
    ],
  },
  {
    book: "mat",
    chapter: 5,
    verses: [
      [3, "Berbahagialah orang yang miskin di hadapan Allah, karena merekalah yang empunya Kerajaan Sorga."],
      [4, "Berbahagialah orang yang berdukacita, karena mereka akan dihibur."],
      [5, "Berbahagialah orang yang lemah lembut, karena mereka akan memiliki bumi."],
      [6, "Berbahagialah orang yang lapar dan haus akan kebenaran, karena mereka akan dipuaskan."],
      [7, "Berbahagialah orang yang murah hati, karena mereka akan beroleh kemurahan."],
      [8, "Berbahagialah orang yang suci hatinya, karena mereka akan melihat Allah."],
      [9, "Berbahagialah orang yang membawa damai, karena mereka akan disebut anak-anak Allah."],
    ],
  },
  {
    book: "mat",
    chapter: 6,
    verses: [
      [33, "Tetapi carilah dahulu Kerajaan Allah dan kebenarannya, maka semuanya itu akan ditambahkan kepadamu."],
      [34, "Sebab itu janganlah kamu khawatir akan hari besok, karena hari besok mempunyai kesusahannya sendiri. Kesusahan sehari cukuplah untuk sehari."],
    ],
  },
  {
    book: "yoh",
    chapter: 1,
    verses: [
      [1, "Pada mulanya adalah Firman, Firman itu bersama-sama dengan Allah, dan Firman itu adalah Allah."],
      [2, "Ia pada mulanya bersama-sama dengan Allah."],
      [3, "Segala sesuatu dijadikan oleh Dia, dan tanpa Dia tidak ada suatu pun yang telah jadi dari segala yang telah dijadikan."],
      [4, "Dalam Dia ada hidup, dan hidup itu adalah terang manusia."],
      [5, "Terang itu bercahaya di dalam kegelapan, dan kegelapan itu tidak menguasainya."],
      [9, "Terang yang sesungguhnya, yang menerangi setiap orang, sedang datang ke dalam dunia."],
      [12, "Tetapi semua orang yang menerimanya diberi-Nya kuasa menjadi anak-anak Allah, yaitu mereka yang percaya dalam nama-Nya."],
      [14, "Firman itu telah menjadi manusia, dan diam di antara kita, penuh kasih karunia dan kebenaran; kami telah melihat kemuliaan-Nya, kemuliaan yang diberikan sebagai Anak Tunggal Bapa."],
    ],
  },
  {
    book: "yoh",
    chapter: 3,
    verses: [
      [16, "Karena begitu besar kasih Allah akan dunia ini, sehingga Ia mengaruniakan Anak-Nya yang tunggal, supaya setiap orang yang percaya kepada-Nya tidak binasa, melainkan beroleh hidup yang kekal."],
      [17, "Sebab Allah mengutus Anak-Nya ke dalam dunia bukan untuk menghakimi dunia, melainkan supaya dunia diselamatkan oleh-Nya."],
    ],
  },
  {
    book: "yoh",
    chapter: 14,
    verses: [
      [1, "Janganlah gelisah hatimu; percayalah kepada Allah, percayalah juga kepada-Ku."],
      [6, "Kata Yesus kepadanya, \"Akulah jalan, kebenaran, dan hidup. Tidak ada seorang pun yang datang kepada Bapa, kalau tidak melalui Aku.\""],
      [27, "Damai sejahtera Kutinggalkan bagimu, damai sejahtera-Ku Kuberikan kepadamu; tidak seperti yang diberikan dunia, Aku berikan kepadamu. Janganlah gelisah dan gentar hatimu."],
    ],
  },
  {
    book: "rm",
    chapter: 8,
    verses: [
      [28, "Kita tahu sekarang, bahwa Allah turut bekerja dalam segala sesuatu untuk mendatangkan kebaikan bagi mereka yang mengasihi Dia, yaitu bagi mereka yang terpanggil sesuai dengan rencana Allah."],
      [31, "Jika Allah di pihak kita, siapakah yang akan melawan kita?"],
      [38, "Sebab aku yakin, bahwa baik maut, maupun hidup, baik malaikat, maupun pemerintah, baik yang ada sekarang, maupun yang akan datang, atau kuasa-kuasa,"],
      [39, "baik yang di atas, maupun yang di bawah, ataupun sesuatu makhluk lain, tidak akan dapat memisahkan kita dari kasih Allah, yang ada dalam Kristus Yesus, Tuhan kita."],
    ],
  },
  {
    book: "1kor",
    chapter: 13,
    verses: [
      [4, "Kasih itu sabar, kasih itu murah hati; ia tidak cemburu, ia tidak memegahkan diri, dan tidak sombong."],
      [5, "Ia tidak melakukan yang tidak sopan, ia tidak mencari keuntungan diri sendiri, ia tidak pemarah, dan tidak menyimpan kesalahan orang lain."],
      [6, "Ia tidak bersukacita karena ketidakadilan, tetapi bersukacita karena kebenaran."],
      [7, "Ia menutupi segala sesuatu, ia percaya segala sesuatu, ia mengharapkan segala sesuatu, ia sabar menanggung segala sesuatu."],
      [8, "Kasih tidak berkesudahan."],
      [13, "Demikianlah tinggal ketiga hal ini, yaitu iman, pengharapan, dan kasih; dan yang paling besar di antaranya ialah kasih."],
    ],
  },
  {
    book: "gal",
    chapter: 5,
    verses: [
      [22, "Tetapi buah Roh ialah kasih, sukacita, damai sejahtera, kesabaran, kemurahan, kebaikan, kesetiaan,"],
      [23, "kelemahlembutan, dan penguasaan diri. Tidak ada hukum yang menentang hal-hal itu."],
    ],
  },
  {
    book: "flp",
    chapter: 4,
    verses: [
      [4, "Bersukacitalah senantiasa dalam Tuhan! Sekali lagi kukatakan: bersukacitalah!"],
      [6, "Janganlah hendaknya kamu khawatir tentang apa pun, tetapi nyatakanlah dalam segala hal keinginanmu kepada Allah dalam doa dan permohonan dengan ucapan syukur."],
      [7, "Damai sejahtera Allah, yang melampaui segala akal, akan memelihara hati dan pikiranmu dalam Kristus Yesus."],
      [8, "Semua yang benar, yang mulia, yang adil, yang suci, yang manis, yang sedap didengar, semua yang disebut kebajikan dan patut dipuji, pikirkanlah semuanya itu."],
      [13, "Segala perkara dapat kutanggung di dalam Dia yang memberi kekuatan kepadaku."],
      [19, "Allahku akan memenuhi segala keperluanmu menurut kekayaan dan kemuliaan-Nya dalam Kristus Yesus."],
    ],
  },
  {
    book: "yak",
    chapter: 1,
    verses: [
      [2, "Anggaplah sebagai suatu kebahagiaan, apabila kamu jatuh ke dalam berbagai-bagai pencobaan,"],
      [3, "sebab kamu tahu, bahwa ujian terhadap imanmu itu menghasilkan ketekunan."],
      [5, "Tetapi apabila di antara kamu ada yang kekurangan hikmat, hendaklah ia memintakannya kepada Allah yang memberikan kepada semua orang dengan murah hati, tanpa mencela, maka hal itu akan diberikan kepadanya."],
      [17, "Setiap pemberian yang baik dan setiap anugerah yang sempurna datangnya dari atas, diturunkan dari Bapa segala terang."],
    ],
  },
  {
    book: "1ptr",
    chapter: 5,
    verses: [
      [6, "Karena itu rendahkanlah dirimu di bawah tangan Allah yang kuat, supaya Ia meninggikan kamu pada waktunya."],
      [7, "Serahkanlah segala kekhawatiranmu kepada-Nya, sebab Ia yang memelihara kamu."],
    ],
  },
  {
    book: "1yoh",
    chapter: 4,
    verses: [
      [18, "Di dalam kasih tidak ada ketakutan, kasih yang sempurna melenyapkan ketakutan."],
      [19, "Kita mengasihi, karena Allah lebih dahulu mengasihi kita."],
    ],
  },
  {
    book: "why",
    chapter: 21,
    verses: [
      [1, "Lalu aku melihat langit yang baru dan bumi yang baru, sebab langit yang pertama dan bumi yang pertama telah berlalu."],
      [4, "Ia akan menghapus segala air mata dari mata mereka, dan maut tidak akan ada lagi; tidak akan ada lagi perkabungan, atau ratap tangis, atau dukacita, sebab segala sesuatu yang lama itu telah berlalu."],
    ],
  },
];
