// Full 66-book Protestant canon skeleton — code, Indonesian name, testament,
// canonical order, and chapter count. Used to seed BibleBook so every book
// and chapter is navigable even where verse text hasn't been loaded yet
// (see seed.ts BIBLE_TEXT for the curated set of chapters/verses with text).
export const BIBLE_BOOKS = [
  // Perjanjian Lama
  { code: "kej", name: "Kejadian", testament: "old", chapterCount: 50 },
  { code: "kel", name: "Keluaran", testament: "old", chapterCount: 40 },
  { code: "im", name: "Imamat", testament: "old", chapterCount: 27 },
  { code: "bil", name: "Bilangan", testament: "old", chapterCount: 36 },
  { code: "ul", name: "Ulangan", testament: "old", chapterCount: 34 },
  { code: "yos", name: "Yosua", testament: "old", chapterCount: 24 },
  { code: "hak", name: "Hakim-hakim", testament: "old", chapterCount: 21 },
  { code: "rut", name: "Rut", testament: "old", chapterCount: 4 },
  { code: "1sam", name: "1 Samuel", testament: "old", chapterCount: 31 },
  { code: "2sam", name: "2 Samuel", testament: "old", chapterCount: 24 },
  { code: "1raj", name: "1 Raja-raja", testament: "old", chapterCount: 22 },
  { code: "2raj", name: "2 Raja-raja", testament: "old", chapterCount: 25 },
  { code: "1taw", name: "1 Tawarikh", testament: "old", chapterCount: 29 },
  { code: "2taw", name: "2 Tawarikh", testament: "old", chapterCount: 36 },
  { code: "ezr", name: "Ezra", testament: "old", chapterCount: 10 },
  { code: "neh", name: "Nehemia", testament: "old", chapterCount: 13 },
  { code: "est", name: "Ester", testament: "old", chapterCount: 10 },
  { code: "ayb", name: "Ayub", testament: "old", chapterCount: 42 },
  { code: "mzm", name: "Mazmur", testament: "old", chapterCount: 150 },
  { code: "ams", name: "Amsal", testament: "old", chapterCount: 31 },
  { code: "pkh", name: "Pengkhotbah", testament: "old", chapterCount: 12 },
  { code: "kid", name: "Kidung Agung", testament: "old", chapterCount: 8 },
  { code: "yes", name: "Yesaya", testament: "old", chapterCount: 66 },
  { code: "yer", name: "Yeremia", testament: "old", chapterCount: 52 },
  { code: "rat", name: "Ratapan", testament: "old", chapterCount: 5 },
  { code: "yeh", name: "Yehezkiel", testament: "old", chapterCount: 48 },
  { code: "dan", name: "Daniel", testament: "old", chapterCount: 12 },
  { code: "hos", name: "Hosea", testament: "old", chapterCount: 14 },
  { code: "yl", name: "Yoel", testament: "old", chapterCount: 3 },
  { code: "am", name: "Amos", testament: "old", chapterCount: 9 },
  { code: "ob", name: "Obaja", testament: "old", chapterCount: 1 },
  { code: "yun", name: "Yunus", testament: "old", chapterCount: 4 },
  { code: "mi", name: "Mikha", testament: "old", chapterCount: 7 },
  { code: "nah", name: "Nahum", testament: "old", chapterCount: 3 },
  { code: "hab", name: "Habakuk", testament: "old", chapterCount: 3 },
  { code: "zef", name: "Zefanya", testament: "old", chapterCount: 3 },
  { code: "hag", name: "Hagai", testament: "old", chapterCount: 2 },
  { code: "za", name: "Zakharia", testament: "old", chapterCount: 14 },
  { code: "mal", name: "Maleakhi", testament: "old", chapterCount: 4 },
  // Perjanjian Baru
  { code: "mat", name: "Matius", testament: "new", chapterCount: 28 },
  { code: "mrk", name: "Markus", testament: "new", chapterCount: 16 },
  { code: "luk", name: "Lukas", testament: "new", chapterCount: 24 },
  { code: "yoh", name: "Yohanes", testament: "new", chapterCount: 21 },
  { code: "kis", name: "Kisah Para Rasul", testament: "new", chapterCount: 28 },
  { code: "rm", name: "Roma", testament: "new", chapterCount: 16 },
  { code: "1kor", name: "1 Korintus", testament: "new", chapterCount: 16 },
  { code: "2kor", name: "2 Korintus", testament: "new", chapterCount: 13 },
  { code: "gal", name: "Galatia", testament: "new", chapterCount: 6 },
  { code: "ef", name: "Efesus", testament: "new", chapterCount: 6 },
  { code: "flp", name: "Filipi", testament: "new", chapterCount: 4 },
  { code: "kol", name: "Kolose", testament: "new", chapterCount: 4 },
  { code: "1tes", name: "1 Tesalonika", testament: "new", chapterCount: 5 },
  { code: "2tes", name: "2 Tesalonika", testament: "new", chapterCount: 3 },
  { code: "1tim", name: "1 Timotius", testament: "new", chapterCount: 6 },
  { code: "2tim", name: "2 Timotius", testament: "new", chapterCount: 4 },
  { code: "tit", name: "Titus", testament: "new", chapterCount: 3 },
  { code: "flm", name: "Filemon", testament: "new", chapterCount: 1 },
  { code: "ibr", name: "Ibrani", testament: "new", chapterCount: 13 },
  { code: "yak", name: "Yakobus", testament: "new", chapterCount: 5 },
  { code: "1ptr", name: "1 Petrus", testament: "new", chapterCount: 5 },
  { code: "2ptr", name: "2 Petrus", testament: "new", chapterCount: 3 },
  { code: "1yoh", name: "1 Yohanes", testament: "new", chapterCount: 5 },
  { code: "2yoh", name: "2 Yohanes", testament: "new", chapterCount: 1 },
  { code: "3yoh", name: "3 Yohanes", testament: "new", chapterCount: 1 },
  { code: "yud", name: "Yudas", testament: "new", chapterCount: 1 },
  { code: "why", name: "Wahyu", testament: "new", chapterCount: 22 },
].map((b, i) => ({ ...b, orderIndex: i + 1 }));
