import { hasRole, isAdmin } from "@/lib/auth/rbac";
import manifest from "./scene-manifest.json";
import type { ScrollWorldConfig, ScrollWorldSection } from "./scrub-engine";

/**
 * The landing page's world: seven scenes the camera travels through, in order,
 * ending on the entrance to the app.
 *
 * Each scene's `still` is generated by `scripts/build-scenes.mjs`. Adding the
 * scroll-scrubbed camera clips later is purely additive — drop the encoded
 * mp4s under `public/scroll-world/clips/`, set `clip` (and `clipMobile`) on
 * each scene and fill in `connectors`. Nothing else changes. See the README.
 */

/**
 * Where each scene's art lives. The committed default points at the SVGs drawn
 * by `scripts/build-scenes.mjs`; `scripts/adopt-scenes.mjs` rewrites entries as
 * you generate real art in Fooocus, one scene at a time. A scene that hasn't
 * been generated keeps its drawing, so a half-finished render session still
 * leaves a coherent page.
 */
const ART: Record<string, { still: string; stillMobile: string }> = manifest;

const SCENE = (id: string) => ART[id].still;
/** The 9:16 cut of the same scene, served on phones. */
const SCENE_M = (id: string) => ART[id].stillMobile;

type Viewer = { signedIn: boolean; role?: string };

/** The scenes, minus the CTA — that depends on who is looking. */
const SCENES: ScrollWorldSection[] = [
  {
    id: "terang",
    label: "Terang",
    still: SCENE("terang"),
    stillMobile: SCENE_M("terang"),
    accent: "#C89B3C",
    scroll: 1.5,
    linger: 0.3,
    eyebrow: "Faith. Every Day. Every Step.",
    title: "Iman yang ditemani, setiap hari.",
    body: "Renungan, Alkitab, doa, dan khotbah dalam satu tempat yang tenang. Tanpa like, tanpa follower, tanpa scroll tanpa akhir.",
    tags: ["Bahasa Indonesia", "Tanpa media sosial", "Mulai gratis"],
  },
  {
    id: "renungan",
    label: "Renungan",
    still: SCENE("renungan"),
    stillMobile: SCENE_M("renungan"),
    accent: "#4FA882",
    eyebrow: "Renungan & khotbah",
    title: "Satu firman untuk hari ini.",
    body: "Renungan tematik dengan alur khotbah singkat — pembuka, merenungkan firman, aplikasi, dan doa penutup. Berbeda setiap hari, siap dibagikan.",
    tags: ["Renungan harian", "Khotbah video", "Mode audio"],
  },
  {
    id: "alkitab",
    label: "Alkitab",
    still: SCENE("alkitab"),
    stillMobile: SCENE_M("alkitab"),
    accent: "#6BCFA0",
    linger: 0.25,
    eyebrow: "Alkitab",
    title: "66 kitab, selalu di tanganmu.",
    body: "Telusuri seluruh kitab, sorot ayat yang menguatkan, tulis catatan pribadi, dan cari apa pun. Unduh untuk dibaca tanpa sinyal.",
    tags: ["Sorot & catatan", "Pencarian", "Bisa offline"],
  },
  {
    id: "doa",
    label: "Doa",
    still: SCENE("doa"),
    stillMobile: SCENE_M("doa"),
    accent: "#D4A853",
    eyebrow: "Pengingat doa",
    title: "Diingatkan dengan lembut, bukan diteriaki.",
    body: "Tentukan waktu doamu sendiri — pagi, siang, malam, atau tengah malam. Livyn menjaga ritmenya dan mencatat langkah yang sudah kamu tempuh.",
    tags: ["Pengingat kustom", "Streak", "Notifikasi push"],
  },
  {
    id: "pastor",
    label: "AI Pastor",
    still: SCENE("pastor"),
    stillMobile: SCENE_M("pastor"),
    accent: "#58B98C",
    eyebrow: "AI Pastor & jurnal",
    title: "Ada yang mendengarkan, kapan pun.",
    body: "Tanya tentang Alkitab, minta ditemani berdoa, atau sekadar curhat kepada Tuhan lewat jurnal — dan pulang membawa satu ayat penguat.",
    tags: ["Tanya jawab", "Jurnal & mood", "Ayat penguat"],
  },
  {
    id: "circle",
    label: "Circle",
    still: SCENE("circle"),
    stillMobile: SCENE_M("circle"),
    accent: "#4FA882",
    eyebrow: "Teman & circle",
    title: "Bertumbuh bersama, bukan sendirian.",
    body: "Undang teman lewat kode unik, kirim ayat penguat, dan bangun circle untuk doa bersama, misi mingguan, dan pesan dari pemimpinmu.",
    tags: ["Verse Ping", "Doa bersama", "Misi mingguan"],
  },
];

/** The last scene carries the entrance, so where it points depends on the
 *  visitor: a signed-in reader goes straight in, everyone else goes through
 *  the splash, which is what decides between onboarding and the login form. */
function finale(viewer: Viewer): ScrollWorldSection {
  const base = {
    id: "mulai",
    label: "Mulai",
    still: SCENE("mulai"),
    stillMobile: SCENE_M("mulai"),
    accent: "#C89B3C",
    scroll: 1.7,
    linger: 0.45,
  } satisfies Partial<ScrollWorldSection> as ScrollWorldSection;

  if (!viewer.signedIn) {
    return {
      ...base,
      eyebrow: "Mulai hari ini",
      title: "Langkah pertamamu, hari ini.",
      body: "Buat akun gratis — atau masuk kalau kamu sudah punya. Semuanya berjalan di browser, tidak ada yang perlu diunduh.",
      cta: {
        primary: { label: "Mulai gratis", href: "/mulai" },
        secondary: { label: "Masuk", href: "/masuk" },
      },
    };
  }

  const role = viewer.role ?? "user";
  const secondary = isAdmin(role)
    ? { label: "Dasbor admin", href: "/admin" }
    : hasRole(role, "contributor")
      ? { label: "Dasbor kontributor", href: "/contributor" }
      : { label: "Renungan hari ini", href: "/app/devosi" };

  return {
    ...base,
    eyebrow: "Selamat datang kembali",
    title: "Perjalananmu menunggu.",
    body: "Renungan hari ini, pengingat doamu, dan circle-mu sudah siap di dalam.",
    cta: { primary: { label: "Buka Livyn", href: "/app" }, secondary },
  };
}

export function livynWorld(viewer: Viewer): ScrollWorldConfig {
  return {
    brand: { name: "Livyn", href: "/" },
    cta: viewer.signedIn
      ? { label: "Buka Livyn", href: "/app" }
      : { label: "Masuk", href: "/masuk" },
    hint: "gulir untuk masuk",
    diveScroll: 1.3,
    connScroll: 0.9,
    sections: [...SCENES, finale(viewer)],
    // No camera clips yet, so no connectors either: the engine cross-dissolves
    // between scenes and slowly pushes each still in as you scroll.
    connectors: [],
  };
}

/** The same copy, for the no-JS fallback and for crawlers. */
export const WORLD_SECTIONS = SCENES;
